export const GET_MOVIES_LIST = "GET_MOVIES_LIST";
export const SUCCESS_MOVIES_LIST = "SUCCESS_MOVIES_LIST";
export const ERROR_MOVIES_LIST = "ERROR_MOVIES_LIST";
export const GET_MOVIE_SELECTED_DETAILS = "GET_MOVIE_SELECTED_DETAILS";
export const UPDATE_MOVIE_SELECTED = "UPDATE_MOVIE_SELECTED";
export const ERROR_MOVIE_SELECTED = "ERROR_MOVIE_SELECTED";
